server.port = 9090
#Database Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/service-provider-onboarding-portal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.connectionTimeout=40000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1200000
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

#Application Configurations
# PDF upload size limit (in KB)
file.pdf.max-size-kb=256
reset.password.url=http://localhost:9090/reset-password
reset.password.expiry.minutes=15
enable.postpaid = false
software.upload.path =C:/ServiceProviderDocuments/
portal.url = http://localhost:9090
portal.name = Service Provider Onboarding Hub




#Spring
server.servlet.context-path=/
server.forward-headers-strategy=framework
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
spring.servlet.multipart.file-size-threshold=2KB



idp.idpUrl=https://offredhat.digitaltrusttech.com/idp/authorization/?
idp.clientId=leEvYKPXrTSRJv0UQfACB0iozBSSvvLgSpDyIIqBuBdKkBPS
idp.clintSecret=MPFjrUq60XO27vwyNSwKSFKwG8Tt0eYPd7Sc5WyQGmVdghAyKeBhXyOz6i4LzwJ7
idp.redirectUri=http://localhost:9090/eoi-redirect
idp.authorizationHeaderName=UgPassAuthorization
idp.openid=false
jwt.clientassertiontype=urn:ietf:params:oauth:client-assertion-type:jwt-bearer
idp.tokenUrl=https://offredhat.digitaltrusttech.com/idp/api/Authentication/token
idp.idpjwkSetURL=https://offredhat.digitaltrusttech.com/idp/api/Jwks/Jwksuri
idp.userInfoUrl=https://offredhat.digitaltrusttech.com/idp/api/UserInfo/userinfo
idp.aud=https://offredhat.digitaltrusttech.com/idp
idp.scope=openid urn:idp:digitalid:profile
privateKey=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDnXv+ZmxTf7u0bskRnaZ9tcrpvfW4kUVz+FEERIQpVw7mPEy+t+k7qUdhfa1fqMujWmRpVZggpmQBZFYXre0ETdYgaJBEPaANWazZrcNDZUkVfElmb8y4Cql5dGSyyCW7s0wcz8mMQ+TiOlw8t3keIsbIjqhYZ5d+ZE6B84V0HWQ6B5sqN0QPwGxH2IB915M7KYVE+mcggLdtzph7Mj+OZ2aNEkY0hwybEGit0T/QFCEeMk1VfUUBhKuQyudR6S8RtnmSRlu/PuBwkubUxnNtpTiSo9dFIDCp27Pbcbxou3afOInqvevravrWOI2GV09nEWmWQY6He6U03kPs3FtITAgMBAAECggEAGlN7391+fZBxGEKrd9zT0B9KyV7LRoSfgSWK1ckdpO6VUYtMVI5zpkPTy9+p7DMIvUpEbc0jRqBrIrfJOicXG4C3EMpjyo36Oz4NviHjEadDz3KGEbGU3abG/+7aYBOktHu6iRWeYhMJdWgIyR5Oo2Ycr+QtiZrXW1KZYzw9WpV3FdsfMAe3kLbMkr0frHZ0RKU1P14EQFOPRFjSZ/Jhggnxs7rWF7jgbeQIjIOHUiNdlqubfNM93NSj5lqA6TTnMixqtvDti9v1DZ6rrskD2sqtCfvTlmPkqwtmiOfkubPoD6QDWJfZaSxlbulRLl4joGk6CORKjhGQRxXlWOBMGQKBgQD/4m3Ps3j+vSXYv2GG4KwbVGRa2xJFJn+4UFoGfJdz7s5GLCFXThSyUzTY+y3fQtcK+s0x457KXow2LuKQy+pqoKhz/a37QeWVrAqZhBqmjbcMIU2mJ5eLcimcBRDPPcA34+BwV6giLdy8b6cM+/smLK78th+kdI8WRXxwA4g7VwKBgQDnebyTEU9HroiyLMPM0DJBlZcBbGCg7wtbi6hq0NGgpJMl+PBnuUhaDJEyu7shcBXZu06G43PAIGayTnX2sEZafA7Mcz1s0eG8jlJNpZa2xQ0pvbJ7c7CPQ2EDbRoOmnGoO2lzrndbO22bfXxck42WW82EuYDgU1ATSeQOAdMlpQKBgCXUevmfBf9bRXIi8S84nhk4Q9Hu22efxnggYP7egqGgJ5zWP2Oh5otqo8CEegas4g/8fkOm7D3s9nu4OMTBcPmsoNrtIUCpQGD9W1/Q2QPQpcREVC+BYPU7vo0TbqXE8lsQ9IiHXRMYhq7RLvhLdJjzODeiUVFF7jWTtk71JrnnAoGAZEQTLxE8aixsAeHqHnnAizAk7PTpFkz1en4QQdSaOR+Qrc4bNJLJiFgRPQycjmtiy6Ga7krwBLUERxA9gNHyZ5d9QYpZfR2cznRHqmKj2h+ZCA+nlFoUjLn+9+D2fITh3qF9mCJmiRpA7C17BQ7VMeAqMee4r3LnKLPFGVwo/hECgYATgf2nhjO5U19hdJ/PZEJCZTBTbfjpz3NjfZsWZ/DG+IOfGV3CY0D5gsN2Ws2hJCsxAg4X5SGP6rMToDy0wbeU/GzayJzlvKnbiqKnLLIO+GxVEkehNz4H7NpBywWpep3o71uT4QgWXzqhGFTz/31sQQiCvf/3lzOCqpV0sWhdVw==
idp.logoutUrl=https://offredhat.digitaltrusttech.com/idp/logout?redirect_uri=http://localhost:9090/logout
url.login.user.photo = https://offredhat.digitaltrusttech.com/idp/api/UserInfo/GetUserImage



#Org
register.organisation = https://offredhat.digitaltrusttech.com/uaeid-migrated/organization/api/post/service/register/organization

organisation.exists = https://offredhat.digitaltrusttech.com/uaeid-migrated/organization/api/get/organization/detailsBy/organizationName?organizationName=

generate.license = https://offredhat.digitaltrusttech.com/uaeid-migrated/organization/api/post/generatelicenses
download.license = https://offredhat.digitaltrusttech.com/uaeid-migrated/organization/api/download/license/
all.license.ouid =https://offredhat.digitaltrusttech.com/uaeid-migrated/organization/api/get-All/licenses/by/ouid/

#Python
send.email.url=http://localhost:5006/sendbodySSPVG

#Admin
url.getEmaillist= https://uaeid-stg.digitaltrusttech.com/uaeid-admin-portal/api/Users/GetAdminUsersList
# max.adminEmails = 0 send all users
max.adminEmails = 4


#Redis session
spring.session.store-type=redis
server.servlet.session.cookie.name=SESSION
server.servlet.session.tracking-modes=cookie


spring.session.timeout=60m
spring.session.redis.repository-type=indexed



app.redis.hosts=127.0.0.1:6379
app.redis.password=
app.redis.username=


url.org.wallet = https://offredhat.digitaltrusttech.com/uaeid-migrated/organization/issue-wallet-certificate
url.find.duplicate.ref.no = https://offredhat.digitaltrusttech.com/uaeid-migrated/organization/api/find/duplicate/reference/id
url.get.wallet.by.ouid = https://offredhat.digitaltrusttech.com/uaeid-migrated/organization/api/get/wallet/cert/by/ouid


spoc.details = https://offredhat.digitaltrusttech.com/uaeid-migrated/On-Boarding/api/get/subscriber/details/emailId/


wallet.cert = false
wallet.cert.payment = false
wallet.cert.Admin.approval = false


